Update codemagic.yaml enabling build triggers

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -2,7 +2,7 @@ workflows:
   release-android:
     name: Build for Google Play
     max_build_duration: 10
-    instance_type: mac_mini
+    instance_type: mac_mini_m1
     environment:
       groups:
         - keystore_credentials # <-- (Includes CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_PASSWORD, CM_KEY_ALIAS)
@@ -10,25 +10,23 @@ workflows:
         - other
       # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
       node: latest
-    # triggering:
-    #   events:
-    #     - push
-    #     - tag
-    #     - pull_request
-    #   branch_patterns:
-    #     - pattern: develop
-    #       include: true
-    #       source: true
+    triggering:
+      events:
+        - push
+      branch_patterns:
+        - pattern: release
+          include: true
+          source: true
     scripts:
       - name: Install npm dependencies
         script: |
-                    npm install
+          npm install
       - name: Build React app
         script: |
-                    npm run build
+          npm run build
       - name: Set Android SDK location
         script: |
-                    echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
+          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
       - name: Set up keystore
         script: |
           echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
@@ -37,17 +35,26 @@ workflows:
           keyPassword=$CM_KEY_PASSWORD
           keyAlias=$CM_KEY_ALIAS
           storeFile=/tmp/keystore.keystore
-          EOF          
+          EOF
       - name: Update dependencies and copy web assets to native project
         script: |
           # npx cap copy # <- use this is you don't need to update native dependencies
-          npx cap sync # <- update native dependencies and copy web assets to native project          
+          npx cap sync # <- update native dependencies and copy web assets to native project
       - name: Build Android release
         script: |
           cd android
-          ./gradlew assembleRelease          
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name 'io.codemagic.androidhelloworldapp')
+          if [ -z LATEST_BUILD_NUMBER ]; then
+            # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+            # UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+            exit 1
+          else
+            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+          fi
+          # provide build number and version through project properties
+          ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER
     artifacts:
-      - android/app/build/outputs/**/*.apk
+      - android/app/build/**/outputs/**/*.aab
     publishing:
       google_play:
         credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
@@ -56,12 +63,12 @@ workflows:
         recipients:
           - campus@oliverrm.de
         notify:
-          success: true     # To not receive a notification when a build succeeds
-          failure: true     # To not receive a notification when a build fails
+          success: true # To not receive a notification when a build succeeds
+          failure: true # To not receive a notification when a build fails
   release-ios:
     name: Build for App Store Connect
     max_build_duration: 10
-    instance_type: mac_mini
+    instance_type: mac_mini_m1
     environment:
       groups:
         # - manual_code_signing # <-- (Includes CM_CERTIFICATE, CM_CERTIFICATE_PASSWORD, CM_PROVISIONING_PROFILE)
@@ -71,35 +78,35 @@ workflows:
       # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
       vars:
         # Ionic Capacitor Xcode worskspace and scheme
-        XCODE_WORKSPACE: "ios/App/App.xcworkspace" # <- Update with your workspace name
-        XCODE_SCHEME: "App" # <- Update with your workspace scheme
+        XCODE_WORKSPACE: 'ios/App/App.xcworkspace' # <- Update with your workspace name
+        XCODE_SCHEME: 'App' # <- Update with your workspace scheme
       node: latest
       xcode: latest
       cocoapods: default
-    # triggering:
-    #   events:
-    #     - push
-    #   branch_patterns:
-    #     - pattern: develop
-    #       include: true
-    #       source: true
+    triggering:
+      events:
+        - push
+      branch_patterns:
+        - pattern: release
+          include: true
+          source: true
     scripts:
       - name: Install npm dependencies for Ionic project
         script: |
-                    npm install
+          npm install
       - name: Build React app
         script: |
-                    npm run build
+          npm run build
       - name: Update dependencies and copy web assets to native project
         script: |
-                    # npx cap copy # <- use this is you don't need to update native dependencies
-                    npx cap sync # <- update native dependencies and copy web assets to native project     
+          # npx cap copy # <- use this is you don't need to update native dependencies
+          npx cap sync # <- update native dependencies and copy web assets to native project
       - name: Cocoapods installation
         script: |
-                    cd ios/App && pod install     
+          cd ios/App && pod install
       - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
         script: |
-                    keychain initialize
+          keychain initialize
       # - name: Set up Provisioning profiles from environment variables (Use with manual code signing)
       #   script: |
       #     PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
@@ -110,37 +117,37 @@ workflows:
       - name: Fetch signing files
         script: |
           # app-store-connect fetch-signing-files "com.nevercode.ncionicapp" --type IOS_APP_STORE --create
-          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) --type IOS_APP_STORE --create          
+          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) --type IOS_APP_STORE --create
       - name: Add certificates to keychain
         script: |
-                    keychain add-certificates
+          keychain add-certificates
       - name: Increment build number
         script: |
           #!/bin/sh
           set -e
           set -x
           cd $CM_BUILD_DIR/ios/App
-          agvtool new-version -all $(($BUILD_NUMBER +1))          
+          agvtool new-version -all $(($BUILD_NUMBER +1))
       - name: Set up code signing settings on Xcode project
         script: |
-                    xcode-project use-profiles
+          xcode-project use-profiles
       - name: Build ipa for distribution
         script: |
-                    xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
+          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
     artifacts:
-        - build/ios/ipa/*.ipa
-        - /tmp/xcodebuild_logs/*.log
-        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
-        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
+      - build/ios/ipa/*.ipa
+      - /tmp/xcodebuild_logs/*.log
+      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
+      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
     publishing:
       app_store_connect:
-          api_key: $APP_STORE_CONNECT_PRIVATE_KEY      # Contents of the API key
-          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER    # Alphanumeric value that identifies the API key
-          issuer_id: $APP_STORE_CONNECT_ISSUER_ID      # Alphanumeric value that identifies who created the API key
-          submit_to_testflight: true        # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight to automatically enroll your build to beta testers.  
+        api_key: $APP_STORE_CONNECT_PRIVATE_KEY # Contents of the API key
+        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER # Alphanumeric value that identifies the API key
+        issuer_id: $APP_STORE_CONNECT_ISSUER_ID # Alphanumeric value that identifies who created the API key
+        submit_to_testflight: true # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight to automatically enroll your build to beta testers.
       email:
         recipients:
           - campus@oliverrm.de
         notify:
-          success: true     # To not receive a notification when a build succeeds
-          failure: true     # To not receive a notification when a build fails
+          success: true # To not receive a notification when a build succeeds
+          failure: true # To not receive a notification when a build fails
